In [1]:
import torch


In [2]:
input_tokens = torch.tensor([2, 5, 1, 9])

In [3]:
vocab_size = 10

In [4]:
output_dim = 3

In [5]:
#intantiatiate an embedding layer
torch.manual_seed(123)
embedding_layer = torch.nn.Embedding(vocab_size, output_dim)


In [6]:
embedding_layer.weight

Parameter containing:
tensor([[ 0.3374, -0.1778, -0.3035],
        [-0.5880,  0.3486,  0.6603],
        [-0.2196, -0.3792,  0.7671],
        [-1.1925,  0.6984, -1.4097],
        [ 0.1794,  1.8951,  1.3689],
        [-1.6033, -1.3250,  0.1784],
        [-2.1338,  1.0524, -0.3885],
        [-0.9343,  1.8319, -0.3378],
        [ 0.8805,  1.5542,  0.6266],
        [-0.1755,  0.0983, -0.0935]], requires_grad=True)

In [7]:
embedding_layer(torch.tensor([3]))

tensor([[-1.1925,  0.6984, -1.4097]], grad_fn=<EmbeddingBackward0>)

In [8]:
embedding_layer(input_tokens)

tensor([[-0.2196, -0.3792,  0.7671],
        [-1.6033, -1.3250,  0.1784],
        [-0.5880,  0.3486,  0.6603],
        [-0.1755,  0.0983, -0.0935]], grad_fn=<EmbeddingBackward0>)

In [9]:
from torch.utils.data import Dataset, DataLoader
import tiktoken

In [10]:
class GPTDataset(Dataset):
    def __init__(self, txt, tokenizer, maxLength, stride):
        self.inputIds = []
        self.targetIds = []
        
       
        tokenIds = tokenizer.encode(txt)
        
        for i in range(0, len(tokenIds) - maxLength, stride):
            inputChunk = tokenIds[i:i+maxLength]
            targetChunk = tokenIds[i+1:i+maxLength+1]
            self.inputIds.append(torch.tensor(inputChunk))
            self.targetIds.append(torch.tensor(targetChunk))
            
            
    def __len__(self):
        return len(self.inputIds)
    
    def __getitem__(self, index):
        return self.inputIds[index], self.targetIds[index]
            

In [11]:
def createDataLoader(text, batch_size = 4, max_length = 256, stride = 128, shuffle = True, drop_last=True, num_workers=0):
    tokenizer = tiktoken.get_encoding('gpt2')
    
    dataset = GPTDataset(text, tokenizer, max_length, stride)
    
    dataloader = DataLoader(
        dataset, 
        batch_size=batch_size,
        shuffle = shuffle,
        drop_last=drop_last,
        num_workers=num_workers
    )
    
    return dataloader

In [12]:
vocab_size = 50000
output_dim = 256

token_embedding_layer = torch.nn.Embedding(vocab_size, output_dim)

In [13]:
token_embedding_layer

Embedding(50000, 256)