In [1]:
import torch

In [2]:
inputs = torch.tensor(
[[0.43, 0.15, 0.89], # Your (x^1)
[0.55, 0.87, 0.66], # journey (x^2)
[0.57, 0.85, 0.64], # starts (x^3)
[0.22, 0.58, 0.33], # with (x^4)
[0.77, 0.25, 0.10], # one (x^5)
[0.05, 0.80, 0.55]] # step (x^6)
)

In [3]:
#1. to calculate omeng (embedded query token)

query = inputs[1]
query


tensor([0.5500, 0.8700, 0.6600])

In [4]:
attn_scores2 = torch.empty(inputs.shape[0])
attn_scores2

tensor([1.1636e-13, 7.7912e-43, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00])

In [5]:
for i, x_i in enumerate(inputs):
  attn_scores2[i] = torch.dot(x_i, query)


attn_scores2

tensor([0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865])

In [6]:
#2. normalize each of the attention scores

attn_weight2 = attn_scores2/attn_scores2.sum()

print("Attention Weights: ", attn_weight2)
print("Attention weight sum : ", attn_weight2.sum())

Attention Weights:  tensor([0.1455, 0.2278, 0.2249, 0.1285, 0.1077, 0.1656])
Attention weight sum :  tensor(1.0000)


In [7]:

#using exponential funtion
attn_weight2_exp = torch.exp(attn_scores2)/torch.exp(attn_scores2).sum()

attn_weight2_exp

tensor([0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581])

In [8]:
attn_weight2_exp.sum()

tensor(1.)

In [9]:
#3. to calcualte context vector

attn_weight2[1] *inputs[1]

tensor([0.1253, 0.1982, 0.1504])

In [10]:
context_vec2 = torch.zeros(query.shape)
for i, x_i in enumerate(inputs):
  context_vec2 += attn_weight2[i] *x_i

print(context_vec2)


tensor([0.4355, 0.6451, 0.5680])


## Computing attention weights for all input tokens

In [13]:
attn_scores = torch.empty(6,6)

In [14]:
for i, x_i in enumerate(inputs):
    for j, x_j in enumerate(inputs):
        attn_scores[i,j] = torch.dot(x_i, x_j)
print(attn_scores)

tensor([[0.9995, 0.9544, 0.9422, 0.4753, 0.4576, 0.6310],
        [0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865],
        [0.9422, 1.4754, 1.4570, 0.8296, 0.7154, 1.0605],
        [0.4753, 0.8434, 0.8296, 0.4937, 0.3474, 0.6565],
        [0.4576, 0.7070, 0.7154, 0.3474, 0.6654, 0.2935],
        [0.6310, 1.0865, 1.0605, 0.6565, 0.2935, 0.9450]])
